---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/eternao4/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp /img $DEPLOYPATH
    - /bin/cp /pages $DEPLOYPATH
    - /bin/cp /includes $DEPLOYPATH
    - /bin/cp /node_modules $DEPLOYPATH
